[package]
name = "end2end"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
rstest = "0.25.0"
